### ISSUE TITLE
Estou com esse problema após editar os ids no arquivo settings.json

### ISSUE THREAD

**Issue by LeonardoSantos123** [rocketmta/redshift#5]
![image](https://user-images.githubusercontent.com/62783168/179885226-2f63a41a-54f0-48bd-941d-fb4007eb5591.png)

**Comment by itsflashii** [comment]
Forneça em um comentário a parte de IDS de seu settings.json


Exemplo: 
```
  "GROUP_ID": "940660578437955614",
  "BOARD_CHANNEL": "980411110014484510",
  "AUTO_ROLE": "978213540584366080",
  "STAFF_ROLE": "978213901562957835",
  "rules": "980329082799661056",
  "spoilers": "958538390561779733",
  "anunc": "951243918756958229",
  "memberCount": "980765267992911872",
  "leaderboard": "980411110014484510",
```

**Comment by LeonardoSantos123** [comment]
"PREFIX": "r.",
  "GROUP_ID": "707674472060158004",
  "BOARD_CHANNEL": "707675473119019039",
  "AUTO_ROLE": "707675455687229521",
  "STAFF_ROLE": "710006438759759972",
  "rules": "980329082799661056",
  "spoilers": "958538390561779733",
  "anunc": "951243918756958229",
  "memberCount": "999141620979081256",
  "leaderboard": "980411110014484510",

**Comment by itsflashii** [comment]
> "PREFIX": "r.", "GROUP_ID": "707674472060158004", "BOARD_CHANNEL": "707675473119019039", "AUTO_ROLE": "707675455687229521", "STAFF_ROLE": "710006438759759972", "rules": "980329082799661056", "spoilers": "958538390561779733", "anunc": "951243918756958229", "memberCount": "999141620979081256", "leaderboard": "980411110014484510",

Ao meu ver, você pode ter cometido um erro de digitação alguns cargos como

- STAFF_ROLE
- AUTO_ROLE

São ids de salas e não cargos, todos os cargos começam com o prefixo 9 e não com 7.. tente verificar e tente novamente, se caso o erro persistir envie seu settings.json completo. Outro ponto que você pode ter cometido e não ter alterado alguns ids, como
"leaderboard": "980411110014484510", não estão alterados e por isso podem causar problemas na inicialização.

**Comment by LeonardoSantos123** [comment]
> > "PREFIX": "r.", "GROUP_ID": "707674472060158004", "BOARD_CHANNEL": "707675473119019039", "AUTO_ROLE": "707675455687229521", "STAFF_ROLE": "710006438759759972", "rules": "980329082799661056", "spoilers": "958538390561779733", "anunc": "951243918756958229", "memberCount": "999141620979081256", "leaderboard": "980411110014484510",
> 
> Ao meu ver, você pode ter cometido um erro de digitação alguns cargos como
> 
> * STAFF_ROLE
> * AUTO_ROLE
> 
> São ids de salas e não cargos, todos os cargos começam com o prefixo 9 e não com 7.. tente verificar e tente novamente, se caso o erro persistir envie seu settings.json completo. Outro ponto que você pode ter cometido e não ter alterado alguns ids, como `"leaderboard": "980411110014484510",` não estão alterados e por isso podem causar problemas na inicialização.

STAFF_ROLE e AUTO_ROLE são cargos?

**Comment by itsflashii** [comment]
> > > "PREFIX": "r.", "GROUP_ID": "707674472060158004", "BOARD_CHANNEL": "707675473119019039", "AUTO_ROLE": "707675455687229521", "STAFF_ROLE": "710006438759759972", "rules": "980329082799661056", "spoilers": "958538390561779733", "anunc": "951243918756958229", "memberCount": "999141620979081256", "leaderboard": "980411110014484510",
> > 
> > 
> > Ao meu ver, você pode ter cometido um erro de digitação alguns cargos como
> > 
> > * STAFF_ROLE
> > * AUTO_ROLE
> > 
> > São ids de salas e não cargos, todos os cargos começam com o prefixo 9 e não com 7.. tente verificar e tente novamente, se caso o erro persistir envie seu settings.json completo. Outro ponto que você pode ter cometido e não ter alterado alguns ids, como `"leaderboard": "980411110014484510",` não estão alterados e por isso podem causar problemas na inicialização.
> 
> STAFF_ROLE e AUTO_ROLE são cargos?

Exato

**Comment by LeonardoSantos123** [comment]
> > > > "PREFIX": "r.", "GROUP_ID": "707674472060158004", "BOARD_CHANNEL": "707675473119019039", "AUTO_ROLE": "707675455687229521", "STAFF_ROLE": "710006438759759972", "rules": "980329082799661056", "spoilers": "958538390561779733", "anunc": "951243918756958229", "memberCount": "999141620979081256", "leaderboard": "980411110014484510",
> > > 
> > > 
> > > Ao meu ver, você pode ter cometido um erro de digitação alguns cargos como
> > > 
> > > * STAFF_ROLE
> > > * AUTO_ROLE
> > > 
> > > São ids de salas e não cargos, todos os cargos começam com o prefixo 9 e não com 7.. tente verificar e tente novamente, se caso o erro persistir envie seu settings.json completo. Outro ponto que você pode ter cometido e não ter alterado alguns ids, como `"leaderboard": "980411110014484510",` não estão alterados e por isso podem causar problemas na inicialização.
> > 
> > 
> > STAFF_ROLE e AUTO_ROLE são cargos?
> 
> Exato

Quando eu clico em copiar id de um cargo, ele vem com o id que começa com 7

**Comment by itsflashii** [comment]
> > > > > "PREFIX": "r.", "GROUP_ID": "707674472060158004", "BOARD_CHANNEL": "707675473119019039", "AUTO_ROLE": "707675455687229521", "STAFF_ROLE": "710006438759759972", "rules": "980329082799661056", "spoilers": "958538390561779733", "anunc": "951243918756958229", "memberCount": "999141620979081256", "leaderboard": "980411110014484510",
> > > > 
> > > > 
> > > > Ao meu ver, você pode ter cometido um erro de digitação alguns cargos como
> > > > 
> > > > * STAFF_ROLE
> > > > * AUTO_ROLE
> > > > 
> > > > São ids de salas e não cargos, todos os cargos começam com o prefixo 9 e não com 7.. tente verificar e tente novamente, se caso o erro persistir envie seu settings.json completo. Outro ponto que você pode ter cometido e não ter alterado alguns ids, como `"leaderboard": "980411110014484510",` não estão alterados e por isso podem causar problemas na inicialização.
> > > 
> > > 
> > > STAFF_ROLE e AUTO_ROLE são cargos?
> > 
> > 
> > Exato
> 
> Quando eu clico em copiar id de um cargo, ele vem com o id que começa com 7

Tente verificar todos os ids, lembre-se que todos os ids precisam ser do seu grupo.

**Comment by LeonardoSantos123** [comment]
Eu coloquei os id dos cargos no STAFF_ROLE e AUTO_ROLE e apareceu esse erro agora:

![image](https://user-images.githubusercontent.com/62783168/179893295-71a927b9-179b-4059-8ea9-e944d2ab58de.png)

**Comment by itsflashii** [comment]
> Eu coloquei os id dos cargos no STAFF_ROLE e AUTO_ROLE e apareceu esse erro agora:
> 
> ![image](https://user-images.githubusercontent.com/62783168/179893295-71a927b9-179b-4059-8ea9-e944d2ab58de.png)

Perfeito, isto é bom! Agora ao meu ver, a única coisa que precisa ser feito é colocar o cargo do bot acima dos outros cargos que ele irá coordenar

![image](https://user-images.githubusercontent.com/85264247/179893935-98c172dc-4c83-41ae-89a5-d6083160df12.png)

**Comment by LeonardoSantos123** [comment]
Agora funcionou, Muito Obrigado <3

**Comment by LeonardoSantos123** [comment]
Agora Funcionou, Muito Obrigado ❤️

**Comment by LeonardoSantos123** [comment]
Quando eu alterei o link das linhas (topImage, topMask), apareceu esse erro:

![image](https://user-images.githubusercontent.com/62783168/179898445-1a0116eb-d74d-40c2-bf81-392da6938328.png)

**Comment by itsflashii** [comment]
> Quando eu alterei o link das linhas (topImage, topMask), apareceu esse erro:
> 
> ![image](https://user-images.githubusercontent.com/62783168/179898445-1a0116eb-d74d-40c2-bf81-392da6938328.png)

Provavelmente esta foto não esta hospedada lembre-se que o link deve terminar com .png | .jpg

**Comment by LeonardoSantos123** [comment]
Aparece esse erro também quando o jogador entra dentro do servidor:

![image](https://user-images.githubusercontent.com/62783168/179899864-cf711f5f-fea8-4516-b87e-f14217d1c3a6.png)

**Comment by itsflashii** [comment]
> Aparece esse erro também quando o jogador entra dentro do servidor:
> 
> ![image](https://user-images.githubusercontent.com/62783168/179899864-cf711f5f-fea8-4516-b87e-f14217d1c3a6.png)

isto é apenas um aviso, e não um erro.. o nome do jogador aparece no card de bem vindo ?

**Comment by LeonardoSantos123** [comment]
> > Aparece esse erro também quando o jogador entra dentro do servidor:
> > ![image](https://user-images.githubusercontent.com/62783168/179899864-cf711f5f-fea8-4516-b87e-f14217d1c3a6.png)
> 
> isto é apenas um aviso, e não um erro.. o nome do jogador aparece no card de bem vindo ?

Sim, mas não aparece em cima a mensagem de "Bem Vindo (a)"

**Comment by itsflashii** [comment]
> > > Aparece esse erro também quando o jogador entra dentro do servidor:
> > > ![image](https://user-images.githubusercontent.com/62783168/179899864-cf711f5f-fea8-4516-b87e-f14217d1c3a6.png)
> > 
> > 
> > isto é apenas um aviso, e não um erro.. o nome do jogador aparece no card de bem vindo ?
> 
> Sim, mas não aparece em cima a mensagem de "Bem Vindo (a)"

Verifique se o board id esta correto, você esta se referindo a imagem ou o texto ?

**Comment by LeonardoSantos123** [comment]
> > > > Aparece esse erro também quando o jogador entra dentro do servidor:
> > > > ![image](https://user-images.githubusercontent.com/62783168/179899864-cf711f5f-fea8-4516-b87e-f14217d1c3a6.png)
> > > 
> > > 
> > > isto é apenas um aviso, e não um erro.. o nome do jogador aparece no card de bem vindo ?
> > 
> > 
> > Sim, mas não aparece em cima a mensagem de "Bem Vindo (a)"
> 
> Verifique se o board id esta correto, você esta se referindo a imagem ou o texto ?

Esses  textos não aparecem:

![Texto_1](https://user-images.githubusercontent.com/62783168/179900364-8a5996e1-3afd-45cd-b495-b33deb900bc0.png)
![Texto_2](https://user-images.githubusercontent.com/62783168/179900374-3ef0d23e-f6cc-4fad-aa45-7a03e6a23a88.png)

**Comment by itsflashii** [comment]
Altere a imagem é provável que a mesma não esteja mais hospedada

**Comment by LeonardoSantos123** [comment]
> Altere a imagem é provável que a mesma não esteja mais hospedada

Eu coloquei as imagens hospedadas dentro do meu discord e copiei o link e mesmo assim elas não aparecem

**Comment by itsflashii** [comment]
> > Altere a imagem é provável que a mesma não esteja mais hospedada
> 
> Eu coloquei as imagens hospedadas dentro do meu discord e copiei o link e mesmo assim elas não aparecem, elas seriam a (topImage e topMask) certo?

Não, é apenas uma no caso a "joinImage"

**Comment by LeonardoSantos123** [comment]
> > > Altere a imagem é provável que a mesma não esteja mais hospedada
> > 
> > 
> > Eu coloquei as imagens hospedadas dentro do meu discord e copiei o link e mesmo assim elas não aparecem, elas seriam a (topImage e topMask) certo?
> 
> Não, é apenas uma no caso a "joinImage"

Aaaaaaa, agora entendi kkkkkk

**Comment by LeonardoSantos123** [comment]
A  topImage e topMask, seriam oq?

**Comment by itsflashii** [comment]
> A topImage e topMask, seriam oq?

leaderboard

**Comment by LeonardoSantos123** [comment]
Eu tenho outra dúvida, como que eu faço pra fazer anúncios através do BOT?

**Comment by itsflashii** [comment]
> Eu tenho outra dúvida, como que eu faço pra fazer anúncios através do BOT?

Tente entrar em contato com algum STAFF via discord, esta issue será fechada por solução do problema, obrigado por usar o Reddshift ❤️

**Comment by LeonardoSantos123** [comment]
Muito obrigado pela ajuda ❤️
